import { randomUUID } from 'node:crypto';
import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { readFile, rename, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { Namespace } from 'socket.io';
import { WebSocket, WebSocketServer } from 'ws';
import { z } from 'zod';
import { runnerSocket } from './runners.js';
import { dataRoot } from './store.js';

export type PreviewRecord={subdomain:string;runnerId:string;userId:string;visible:boolean;createdAt:string;updatedAt:string;expiresAt:string};
const file=path.join(dataRoot,'previews.json');
const records=new Map<string,PreviewRecord>();
const reserved=new Set(['ai','api','admin','npm','portainer','mail','www','autoconfig','autodiscover','quest','arcade','wearly','htlbets','proxy','static']);
const namePattern=/^[a-z0-9](?:[a-z0-9-]{0,30}[a-z0-9])?$/;
const domain=process.env.PREVIEW_BASE_DOMAIN||'s1m4.com';
let saving=Promise.resolve();
const validName=(name:string)=>name.length>=2&&name.length<=32&&namePattern.test(name)&&!reserved.has(name);
const publicUrl=(name:string)=>`https://${name}.${domain}`;

export async function loadPreviews(){try{const rows=JSON.parse(await readFile(file,'utf8')) as PreviewRecord[];for(const row of rows)if(validName(row.subdomain))records.set(row.subdomain,row);}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}}
function persist(){const task=saving.then(async()=>{await writeFile(file+'.tmp',JSON.stringify([...records.values()],null,2),{mode:0o600});await rename(file+'.tmp',file);});saving=task.then(()=>undefined,()=>undefined);return task;}
export function listPreviews(userId:string,runnerId:string){return [...records.values()].filter(r=>r.userId===userId&&r.runnerId===runnerId).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).map(r=>({...r,url:publicUrl(r.subdomain),online:!!runnerSocket(r.runnerId),expired:Date.parse(r.expiresAt)<=Date.now()}));}
export async function setPreviewVisibility(userId:string,runnerId:string,subdomain:string,visible:boolean){const record=records.get(subdomain);if(!record||record.userId!==userId||record.runnerId!==runnerId)return null;record.visible=visible;record.updatedAt=new Date().toISOString();await persist();return {...record,url:publicUrl(subdomain)};}

type PendingHttp={runnerId:string;response:ServerResponse;timer:NodeJS.Timeout};
const pendingHttp=new Map<string,PendingHttp>();
const pendingWs=new Map<string,{runnerId:string;client:WebSocket;ready:boolean;queue:{data:Buffer;binary:boolean}[]}>();
const hopHeaders=new Set(['connection','upgrade','keep-alive','proxy-authenticate','proxy-authorization','te','trailer','transfer-encoding']);
function safeHeaders(raw:Record<string,unknown>){const headers:Record<string,string|string[]>={};for(const [key,value] of Object.entries(raw)){if(hopHeaders.has(key.toLowerCase())||!value)continue;if(typeof value==='string')headers[key]=value;else if(Array.isArray(value)&&value.every(x=>typeof x==='string'))headers[key]=value;}return headers;}
function requestName(req:IncomingMessage){const host=req.headers.host||'',match=host.toLowerCase().match(new RegExp(`^([a-z0-9-]{2,32})\\.${domain.replaceAll('.','\\.')}(?::[0-9]+)?$`));return match&&validName(match[1])?match[1]:null;}
function publicRecord(req:IncomingMessage){const name=requestName(req),record=name?records.get(name):undefined;return record&&record.visible&&Date.parse(record.expiresAt)>Date.now()?record:null;}
function fail(response:ServerResponse,status:number,message:string){if(response.headersSent){response.destroy();return;}response.writeHead(status,{'content-type':'text/plain; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'});response.end(message);}
function finishHttp(id:string){const pending=pendingHttp.get(id);if(!pending)return;clearTimeout(pending.timer);pendingHttp.delete(id);}

export function attachPreviewHandlers(namespace:Namespace){namespace.on('connection',socket=>{
  const runnerId=socket.data.runnerId as string,userId=socket.data.userId as string;
  socket.on('preview:register',async(raw:unknown,ack?:(reply:unknown)=>void)=>{const parsed=z.object({subdomain:z.string(),renew:z.boolean().optional()}).safeParse(raw);if(!parsed.success||!validName(parsed.data.subdomain))return ack?.({ok:false,error:'Недопустимый поддомен'});const name=parsed.data.subdomain,existing=records.get(name);if(existing&&(existing.runnerId!==runnerId||existing.userId!==userId))return ack?.({ok:false,error:'Поддомен уже занят'});const now=new Date().toISOString();const record:PreviewRecord=existing||{subdomain:name,runnerId,userId,visible:true,createdAt:now,updatedAt:now,expiresAt:new Date(Date.now()+7*86400000).toISOString()};if(parsed.data.renew){record.expiresAt=new Date(Date.now()+7*86400000).toISOString();record.updatedAt=now;}records.set(name,record);try{await persist();ack?.({ok:true,url:publicUrl(name),visible:record.visible,expiresAt:record.expiresAt});}catch{ack?.({ok:false,error:'Не удалось сохранить превью'});}});
  socket.on('preview:unregister',async(raw:unknown,ack?:(reply:unknown)=>void)=>{const parsed=z.object({subdomain:z.string()}).safeParse(raw);if(!parsed.success)return ack?.({ok:false});const record=records.get(parsed.data.subdomain);if(!record||record.runnerId!==runnerId||record.userId!==userId)return ack?.({ok:false});records.delete(record.subdomain);await persist();ack?.({ok:true});});
  socket.on('preview:http:headers',(raw:unknown)=>{const parsed=z.object({id:z.string().uuid(),status:z.number().int().min(100).max(599),headers:z.record(z.unknown())}).safeParse(raw);if(!parsed.success)return;const pending=pendingHttp.get(parsed.data.id);if(!pending||pending.runnerId!==runnerId||pending.response.headersSent)return;pending.response.writeHead(parsed.data.status,{...safeHeaders(parsed.data.headers),'cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'no-referrer'});});
  socket.on('preview:http:chunk',(raw:unknown,ack?:(ok:boolean)=>void)=>{const parsed=z.object({id:z.string().uuid(),data:z.any()}).safeParse(raw);if(!parsed.success)return ack?.(false);const pending=pendingHttp.get(parsed.data.id);if(!pending||pending.runnerId!==runnerId)return ack?.(false);const chunk=Buffer.isBuffer(parsed.data.data)?parsed.data.data:parsed.data.data instanceof Uint8Array?Buffer.from(parsed.data.data):null;if(!chunk||chunk.length>128*1024)return ack?.(false);if(pending.response.write(chunk))ack?.(true);else pending.response.once('drain',()=>ack?.(true));});
  socket.on('preview:http:end',(raw:unknown)=>{const parsed=z.object({id:z.string().uuid()}).safeParse(raw);if(!parsed.success)return;const pending=pendingHttp.get(parsed.data.id);if(!pending||pending.runnerId!==runnerId)return;pending.response.end();finishHttp(parsed.data.id);});
  socket.on('preview:http:error',(raw:unknown)=>{const parsed=z.object({id:z.string().uuid()}).safeParse(raw);if(!parsed.success)return;const pending=pendingHttp.get(parsed.data.id);if(!pending||pending.runnerId!==runnerId)return;fail(pending.response,502,'Preview runner error');finishHttp(parsed.data.id);});
  socket.on('preview:ws:frame',(raw:unknown)=>{const parsed=z.object({id:z.string().uuid(),data:z.any(),binary:z.boolean()}).safeParse(raw);if(!parsed.success)return;const pending=pendingWs.get(parsed.data.id);if(!pending||pending.runnerId!==runnerId||pending.client.readyState!==WebSocket.OPEN)return;const data=Buffer.isBuffer(parsed.data.data)?parsed.data.data:parsed.data.data instanceof Uint8Array?Buffer.from(parsed.data.data):null;if(data&&data.length<=2*1024*1024)pending.client.send(data,{binary:parsed.data.binary});});
  socket.on('preview:ws:close',(raw:unknown)=>{const parsed=z.object({id:z.string().uuid()}).safeParse(raw);if(!parsed.success)return;const pending=pendingWs.get(parsed.data.id);if(pending?.runnerId===runnerId){pending.client.close();pendingWs.delete(parsed.data.id);}});
  socket.on('disconnect',()=>{for(const [id,pending] of pendingHttp)if(pending.runnerId===runnerId){fail(pending.response,502,'Preview runner offline');finishHttp(id);}for(const [id,pending] of pendingWs)if(pending.runnerId===runnerId){pending.client.close(1011,'Runner offline');pendingWs.delete(id);}});
});}

export function startPreviewServer(port:number){const server=createServer(async(req,res)=>{const record=publicRecord(req);if(!record)return fail(res,404,'Preview not found');const runner=runnerSocket(record.runnerId);if(!runner)return fail(res,503,'Preview runner offline');if(pendingHttp.size>=100)return fail(res,503,'Too many preview requests');let body=Buffer.alloc(0);try{for await(const part of req){body=Buffer.concat([body,part as Buffer]);if(body.length>2*1024*1024)return fail(res,413,'Request too large');}}catch{return fail(res,400,'Invalid request');}const id=randomUUID(),timer=setTimeout(()=>{fail(res,504,'Preview timed out');finishHttp(id);runner.emit('preview:http:abort',{id});},3600000);pendingHttp.set(id,{runnerId:record.runnerId,response:res,timer});res.on('close',()=>{if(pendingHttp.has(id)){finishHttp(id);runner.emit('preview:http:abort',{id});}});runner.timeout(10000).emit('preview:http:start',{id,subdomain:record.subdomain,method:req.method||'GET',url:req.url||'/',headers:safeHeaders(req.headers),body},(error:Error|null,ack:{ok?:boolean})=>{if(error||!ack?.ok){fail(res,502,'Preview runner unavailable');finishHttp(id);}});});
  const wsServer=new WebSocketServer({noServer:true,maxPayload:2*1024*1024});server.on('upgrade',(req,socket,head)=>{const record=publicRecord(req),runner=record?runnerSocket(record.runnerId):null;if(!record||!runner){socket.write('HTTP/1.1 404 Not Found\r\nConnection: close\r\n\r\n');socket.destroy();return;}wsServer.handleUpgrade(req,socket,head,client=>{const id=randomUUID(),pending={runnerId:record.runnerId,client,ready:false,queue:[] as {data:Buffer;binary:boolean}[]};pendingWs.set(id,pending);client.on('message',(data,binary)=>{const frame={data:Buffer.from(data as Buffer),binary};if(pending.ready)runner.emit('preview:ws:frame',{id,...frame});else if(pending.queue.length<32)pending.queue.push(frame);else client.close(1009,'Too many queued frames');});client.on('close',()=>{pendingWs.delete(id);runner.emit('preview:ws:close',{id});});runner.timeout(10000).emit('preview:ws:open',{id,subdomain:record.subdomain,url:req.url||'/',headers:safeHeaders(req.headers)},(error:Error|null,ack:{ok?:boolean})=>{if(error||!ack?.ok){client.close(1011,'Preview unavailable');return;}pending.ready=true;for(const frame of pending.queue)runner.emit('preview:ws:frame',{id,...frame});pending.queue=[];});});});server.listen(port,'0.0.0.0',()=>console.log(`Preview tunnel ready on ${port}`));return server;}
