import { mkdir, rename, writeFile } from 'node:fs/promises';
import path from 'node:path';

export type CheckpointStatus = 'running' | 'checkpointing' | 'handoff_pending' | 'completed' | 'failed';

export interface TaskCheckpoint {
  version: 1;
  revision: number;
  taskId: string;
  jobId: string;
  accountId: string;
  provider: string;
  sessionId: string;
  projectId?: string;
  model: string;
  reasoning?: string;
  prompt: string;
  status: CheckpointStatus;
  updatedAt: string;
  lastEvent?: string;
  partialText?: string;
  priorContext?: string;
  error?: string;
  handoffReason?: string;
  threadId?: string;
}

const clip = (value: string, length: number) => value.length > length ? value.slice(-length) : value;

async function atomicWrite(file: string, value: string) {
  await mkdir(path.dirname(file), { recursive: true, mode: 0o700 });
  const tmp = `${file}.tmp`;
  await writeFile(tmp, value, { mode: 0o600 });
  await rename(tmp, file);
}

export class CheckpointWriter {
  readonly directory: string;
  readonly file: string;
  readonly handoffFile: string;
  private state: TaskCheckpoint;
  private chain = Promise.resolve();
  private lastWrite = 0;
  private writeError?: Error;
  private scheduled?: NodeJS.Timeout;

  constructor(root: string, taskId: string, initial: Omit<TaskCheckpoint, 'version' | 'revision' | 'status' | 'updatedAt'>) {
    this.directory = path.join(root, '.ai-router', 'tasks', taskId);
    this.file = path.join(this.directory, 'checkpoint.json');
    this.handoffFile = path.join(this.directory, 'HANDOFF.md');
    this.state = { ...initial, version: 1, revision: 0, status: 'running', updatedAt: new Date().toISOString() };
  }

  update(patch: Partial<TaskCheckpoint>, force = false) {
    this.state = { ...this.state, ...patch, revision: this.state.revision + 1, updatedAt: new Date().toISOString() };
    const now = Date.now();
    if (!force && now - this.lastWrite < 750) {
      if (!this.scheduled) this.scheduled = setTimeout(() => { this.scheduled = undefined; this.update({}, true); }, 750 - (now - this.lastWrite));
      return;
    }
    if (this.scheduled) { clearTimeout(this.scheduled); this.scheduled = undefined; }
    this.lastWrite = now;
    const snapshot = { ...this.state };
    this.chain = this.chain.then(async () => {
      const json = JSON.stringify(snapshot, null, 2);
      await atomicWrite(this.file, json);
      await atomicWrite(this.handoffFile, this.markdown(snapshot));
    }).catch(error => { this.writeError = error instanceof Error ? error : new Error(String(error)); });
  }

  async flush() {
    this.update({}, true);
    await this.chain;
    if (this.writeError) throw this.writeError;
  }

  private markdown(state: TaskCheckpoint) {
    return `# AI Router handoff\n\n` +
      `This file is generated by the runner. Read it before continuing the task.\n\n` +
      `- Task: ${state.taskId}\n` +
      `- Session: ${state.sessionId}\n` +
      `- Provider: ${state.provider}\n` +
      `- Account: ${state.accountId}\n` +
      `- Model: ${state.model}\n` +
      `- Reasoning: ${state.reasoning || 'default'}\n` +
      `- Status: ${state.status}\n` +
      `- Updated: ${state.updatedAt}\n` +
      (state.handoffReason ? `- Handoff reason: ${state.handoffReason}\n` : '') +
      `\n## Original request\n\n${clip(state.prompt, 16000)}\n` +
      (state.priorContext ? `\n## Earlier handoffs\n\n${clip(state.priorContext, 20000)}\n` : '') +
      (state.partialText ? `\n## Last provider output\n\n${clip(state.partialText, 12000)}\n` : '') +
      (state.error ? `\n## Error\n\n${clip(state.error, 3000)}\n` : '') +
      `\n## Continuation instructions\n\n` +
      `Inspect the current project files before changing anything. Continue from the existing state; do not repeat completed commands or overwrite valid work. Update this task in the same folder and leave the project in a runnable state.\n`;
  }
}
