import { spawn } from 'node:child_process';
import { access, constants, mkdir } from 'node:fs/promises';
import path from 'node:path';
export type ProviderId='codex'|'antigravity';
export type Job={jobId:string;accountId:string;provider:ProviderId;sessionId:string;prompt:string;model:string;mode:'chat'|'task'};
export type Event={type:'status'|'delta'|'tool'|'usage';text?:string;message?:string;data?:Record<string,unknown>};
export class RunnerError extends Error {constructor(message:string,public code:string){super(message);}}
const root=path.resolve(process.env.RUNNER_DATA_DIR||'/runner-data');
const bin={codex:process.env.CODEX_BIN||'codex',antigravity:process.env.AGY_BIN||'agy'};
async function exists(command:string){const paths=command.includes('/')?[command]:(process.env.PATH||'').split(path.delimiter).map(dir=>path.join(dir,command));for(const p of paths)try{await access(p,constants.X_OK);return true;}catch{}return false;}
function envFor(home:string,provider:ProviderId):NodeJS.ProcessEnv{const env:NodeJS.ProcessEnv={...process.env,HOME:home};if(provider==='codex')env.CODEX_HOME=path.join(home,'.codex');for(const key of ['OPENAI_API_KEY','CODEX_API_KEY','CODEX_ACCESS_TOKEN','GOOGLE_API_KEY','GEMINI_API_KEY','ANTHROPIC_API_KEY'])delete env[key];return env;}
function classify(message:string){const s=message.toLowerCase();if(/transport channel closed|http request failed|rmcp/.test(s))return new RunnerError('Codex не смог подключиться к MCP-сервису провайдера; проверьте сеть контейнера и версию CLI','unavailable');return new RunnerError(message.slice(-700)||'CLI завершился с ошибкой',/rate.?limit|quota|too many requests|usage limit/.test(s)?'rate_limit':/auth|login|sign.in|credential/.test(s)?'auth':'failed');}
function rateLimits(value:any){
  const event=value?.type==='event_msg'&&value.payload?value.payload:value;
  const raw=event?.rate_limits||event?.rateLimits;
  if(!raw||typeof raw!=='object')return null;
  const map=(window:any)=>{
    if(!window||typeof window!=='object')return null;
    const used=Number(window.used_percent??window.usedPercent);
    if(!Number.isFinite(used))return null;
    const minutes=Number(window.window_minutes??window.windowMinutes);
    const reset=window.reset_at??window.resetAt;
    let resetAt: string|undefined;
    if(typeof reset==='number'&&Number.isFinite(reset))resetAt=new Date(reset>10_000_000_000?reset:reset*1000).toISOString();
    else if(typeof reset==='string'&&reset.trim())resetAt=reset;
    else {const seconds=Number(window.resets_in_seconds??window.resetsInSeconds);if(Number.isFinite(seconds))resetAt=new Date(Date.now()+seconds*1000).toISOString();}
    return {usedPercent:used,windowMinutes:Number.isFinite(minutes)?minutes:undefined,resetAt};
  };
  const primary=map(raw.primary||raw.primary_window||raw.primaryWindow),secondary=map(raw.secondary||raw.secondary_window||raw.secondaryWindow);
  return primary||secondary?{primary,secondary}:null;
}
async function runJson(command:string,args:string[],cwd:string,home:string,provider:ProviderId,signal:AbortSignal,onJson:(v:Record<string,any>)=>void){if(signal.aborted)throw new RunnerError('Остановлено','canceled');return new Promise<{code:number;stderr:string}>((resolve,reject)=>{const child=spawn(command,args,{cwd,env:envFor(home,provider),stdio:['ignore','pipe','pipe'],detached:true});let buffer='',stderr='',settled=false;const stop=()=>{if(child.pid){try{process.kill(-child.pid,'SIGTERM');}catch{child.kill('SIGTERM');}setTimeout(()=>{try{process.kill(-child.pid!,'SIGKILL');}catch{}},5000).unref();}};const timer=setTimeout(stop,Number(process.env.CLI_TIMEOUT_SECONDS||180)*1000);signal.addEventListener('abort',stop,{once:true});if(signal.aborted)stop();child.stdout.on('data',(data:Buffer)=>{buffer+=data.toString();let i;while((i=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,i);buffer=buffer.slice(i+1);try{onJson(JSON.parse(line));}catch{}}});child.stderr.on('data',(data:Buffer)=>{stderr=(stderr+data.toString()).slice(-8000);});child.on('error',err=>{if(settled)return;settled=true;clearTimeout(timer);signal.removeEventListener('abort',stop);reject(new RunnerError(err.message,'unavailable'));});child.on('close',code=>{if(settled)return;settled=true;clearTimeout(timer);signal.removeEventListener('abort',stop);if(buffer.trim())try{onJson(JSON.parse(buffer));}catch{}resolve({code:code??1,stderr});});});}
async function codexAuth(home:string){return new Promise<boolean>(resolve=>{const p=spawn(bin.codex,['login','status'],{env:envFor(home,'codex'),stdio:'ignore'});const timer=setTimeout(()=>{p.kill();resolve(false);},5000);p.on('error',()=>{clearTimeout(timer);resolve(false);});p.on('close',code=>{clearTimeout(timer);resolve(code===0);});});}
export async function execute(job:Job,signal:AbortSignal,emit:(e:Event)=>void):Promise<string>{if(signal.aborted)throw new RunnerError('Остановлено','canceled');const home=path.join(root,'accounts',job.accountId,'home'),cwd=path.join(root,'workspaces',job.sessionId);await mkdir(home,{recursive:true,mode:0o700});await mkdir(cwd,{recursive:true,mode:0o700});if(signal.aborted)throw new RunnerError('Остановлено','canceled');const command=bin[job.provider];if(!await exists(command)){if(process.env.MOCK_MODE==='false')throw new RunnerError('CLI не установлен','unavailable');const text=`Демо-ответ (${job.provider}): «${job.prompt.slice(0,300)}». Установите CLI в контейнере исполнителя и войдите в аккаунт для реального ответа.`;emit({type:'status',message:'Демо-режим: CLI не установлен'});for(const chunk of text.match(/.{1,24}/gu)||[text]){if(signal.aborted)throw new RunnerError('Остановлено','canceled');emit({type:'delta',text:chunk});await new Promise(r=>setTimeout(r,35));}return text;}
 if(job.provider==='codex'){if(!await codexAuth(home))throw new RunnerError('Требуется вход через codex login','auth');if(signal.aborted)throw new RunnerError('Остановлено','canceled');let text='';const args=['exec','--json','--ignore-user-config','--skip-git-repo-check','--sandbox',job.mode==='task'?'workspace-write':'read-only'];if(job.model!=='default')args.push('--model',job.model);args.push(job.prompt);const result=await runJson(command,args,cwd,home,'codex',signal,j=>{const limits=rateLimits(j);if(limits)emit({type:'usage',data:{limits}});if(j.type==='item.completed'&&j.item?.type==='agent_message'&&typeof j.item.text==='string'){text=j.item.text;emit({type:'delta',text});}else if(j.type==='item.started'&&j.item?.type==='command_execution')emit({type:'tool',message:'Команда CLI',data:{command:String(j.item.command||'').slice(0,300)}});else if(j.type==='turn.completed'&&j.usage)emit({type:'usage',data:j.usage});});if(signal.aborted)throw new RunnerError('Остановлено','canceled');if(result.code!==0||!text.trim())throw classify(result.stderr||'CLI не вернул ответ');return text;}
 let text='',streamed='',status='',failure='';const args=['-p',job.prompt,'--output-format','stream-json','--mode',job.mode==='task'?'accept-edits':'plan'];if(job.model!=='default')args.push('--model',job.model);const result=await runJson(command,args,cwd,home,'antigravity',signal,j=>{if(j.event==='step_update'){const step=j.step_update||{};if(step.step_type==='tool')emit({type:'tool',message:String(step.tool_name||'Инструмент'),data:{state:step.state}});if(step.step_type==='agent_response'&&typeof step.text_delta==='string'){streamed+=step.text_delta;emit({type:'delta',text:step.text_delta});}}else if(j.event==='result'){const r=j.result||j;text=String(r.response||'');status=String(r.status||'');failure=String(r.error||'');if(text&&!streamed)emit({type:'delta',text});if(r.usage)emit({type:'usage',data:r.usage});}});if(signal.aborted)throw new RunnerError('Остановлено','canceled');if(result.code!==0||status&&status!=='SUCCESS'||!text.trim())throw classify(result.stderr||failure||status||'CLI не вернул ответ');return text;
}
