import { createReadStream } from 'node:fs';
import { chmod, mkdir, readFile, realpath, rename, stat, unlink, writeFile } from 'node:fs/promises';
import { request as httpRequest } from 'node:http';
import { createServer, type Socket as NetSocket } from 'node:net';
import path from 'node:path';
import type { Socket } from 'socket.io-client';
import { WebSocket } from 'ws';
import { z } from 'zod';

const dataRoot=path.resolve(process.env.RUNNER_DATA_DIR||'/runner-data');
const registryFile=path.join(dataRoot,'previews.json');
const controlFile=path.join(dataRoot,'preview-control.sock');
type Target={kind:'static';root:string}|{kind:'port';port:number};
type Saved={subdomain:string;target:Target};
const targets=new Map<string,Target>();
const requestSchema=z.object({id:z.string().uuid(),subdomain:z.string(),method:z.string().max(16),url:z.string().max(4096),headers:z.record(z.unknown()),body:z.any()});
const wsSchema=z.object({id:z.string().uuid(),subdomain:z.string(),url:z.string().max(4096),headers:z.record(z.unknown())});
const commandSchema=z.discriminatedUnion('action',[
  z.object({action:z.literal('publish'),subdomain:z.string().regex(/^[a-z0-9-]{2,32}$/),target:z.discriminatedUnion('kind',[z.object({kind:z.literal('static'),root:z.string().min(1)}),z.object({kind:z.literal('port'),port:z.number().int().min(1024).max(65535)})])}),
  z.object({action:z.literal('stop'),subdomain:z.string()}),
  z.object({action:z.literal('list')})
]);
const types:Record<string,string>={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.gif':'image/gif','.webp':'image/webp','.ico':'image/x-icon','.woff':'font/woff','.woff2':'font/woff2','.ttf':'font/ttf','.wasm':'application/wasm','.txt':'text/plain; charset=utf-8','.map':'application/json; charset=utf-8','.webmanifest':'application/manifest+json'};
const hop=new Set(['host','connection','upgrade','keep-alive','proxy-authenticate','proxy-authorization','te','trailer','transfer-encoding','content-length']);
function localHeaders(raw:Record<string,unknown>,port:number){const headers:Record<string,string|string[]>={host:`127.0.0.1:${port}`};for(const [key,value] of Object.entries(raw)){if(hop.has(key.toLowerCase())||key.toLowerCase().startsWith('sec-websocket-')||!value)continue;if(typeof value==='string')headers[key]=value;else if(Array.isArray(value)&&value.every(x=>typeof x==='string'))headers[key]=value;}headers['x-forwarded-host']=String(raw.host||'');headers['x-forwarded-proto']='https';return headers;}
async function save(){await mkdir(dataRoot,{recursive:true,mode:0o700});await writeFile(registryFile+'.tmp',JSON.stringify([...targets].map(([subdomain,target])=>({subdomain,target}))),{mode:0o600});await rename(registryFile+'.tmp',registryFile);}
function within(file:string,base:string){return file===base||file.startsWith(base+path.sep);}
async function checkedStaticRoot(input:string){const resolved=await realpath(input);const allowed=await Promise.all(['projects','workspaces'].map(async part=>{try{return await realpath(path.join(dataRoot,part));}catch{return path.join(dataRoot,part);}}));if(!allowed.some(base=>within(resolved,base)))throw new Error('Публиковать можно только папки проектов и чатов runner');if(!(await stat(resolved)).isDirectory())throw new Error('Укажите папку сайта');if(!(await stat(path.join(resolved,'index.html')).catch(()=>null))?.isFile())throw new Error('В папке нет index.html');return resolved;}
async function staticFile(root:string,url:string){let pathname:string;try{pathname=decodeURIComponent(new URL(url,'http://preview.local').pathname);}catch{return null;}if(pathname.includes('\\')||pathname.split('/').some(part=>part.startsWith('.')))return null;let candidate=path.resolve(root,'.'+pathname);if(!within(candidate,root))return null;let info=await stat(candidate).catch(()=>null);if(info?.isDirectory()){candidate=path.join(candidate,'index.html');info=await stat(candidate).catch(()=>null);}if(!info?.isFile()){candidate=path.join(root,'index.html');info=await stat(candidate).catch(()=>null);}if(!info?.isFile())return null;const actual=await realpath(candidate);return within(actual,root)?{file:actual,size:info.size}:null;}
async function registerSaved(socket:Socket){for(const subdomain of targets.keys())try{await socket.timeout(10000).emitWithAck('preview:register',{subdomain,renew:false});}catch(error){console.error(`Preview ${subdomain} registration failed:`,error instanceof Error?error.message:error);}}

export async function startPreviews(socket:Socket){await mkdir(dataRoot,{recursive:true,mode:0o700});try{const saved=JSON.parse(await readFile(registryFile,'utf8')) as Saved[];for(const item of saved)if(item?.subdomain&&item.target)targets.set(item.subdomain,item.target);}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')console.error('Preview registry unreadable:',error);}
  socket.on('connect',()=>{void registerSaved(socket);});if(socket.connected)void registerSaved(socket);
  const aborters=new Map<string,()=>void>();
  const emitHeaders=(id:string,status:number,headers:Record<string,unknown>)=>socket.emit('preview:http:headers',{id,status,headers});
  const emitChunk=async(id:string,data:Buffer)=>{const ok=await socket.timeout(15000).emitWithAck('preview:http:chunk',{id,data});if(!ok)throw new Error('Preview client disconnected');};
  const serveStatic=async(id:string,root:string,method:string,url:string)=>{if(method!=='GET'&&method!=='HEAD'){emitHeaders(id,405,{'content-type':'text/plain'});socket.emit('preview:http:end',{id});return;}const file=await staticFile(root,url);if(!file){emitHeaders(id,404,{'content-type':'text/plain'});socket.emit('preview:http:end',{id});return;}emitHeaders(id,200,{'content-type':types[path.extname(file.file).toLowerCase()]||'application/octet-stream','content-length':String(file.size)});if(method!=='HEAD'){const stream=createReadStream(file.file,{highWaterMark:64*1024});aborters.set(id,()=>stream.destroy());for await(const chunk of stream)await emitChunk(id,chunk as Buffer);}socket.emit('preview:http:end',{id});};
  const servePort=async(id:string,port:number,method:string,url:string,headers:Record<string,unknown>,body:Buffer)=>{await new Promise<void>((resolve,reject)=>{const request=httpRequest({hostname:'127.0.0.1',port,path:url,method,headers:localHeaders(headers,port),timeout:3600000},response=>{emitHeaders(id,response.statusCode||502,response.headers);void(async()=>{try{for await(const part of response)await emitChunk(id,part as Buffer);socket.emit('preview:http:end',{id});resolve();}catch(error){reject(error);}})();});aborters.set(id,()=>request.destroy());request.on('error',reject);request.on('timeout',()=>request.destroy(new Error('Local site timed out')));request.end(body);});};
  socket.on('preview:http:start',(raw:unknown,ack?:(reply:unknown)=>void)=>{const parsed=requestSchema.safeParse(raw),target=parsed.success?targets.get(parsed.data.subdomain):undefined;if(!parsed.success||!target)return ack?.({ok:false});const {id,method,url,headers}=parsed.data,body=Buffer.isBuffer(parsed.data.body)?parsed.data.body:Buffer.from(parsed.data.body||[]);if(body.length>2*1024*1024)return ack?.({ok:false});ack?.({ok:true});void(async()=>{try{if(target.kind==='static')await serveStatic(id,target.root,method,url);else await servePort(id,target.port,method,url,headers,body);}catch(error){socket.emit('preview:http:error',{id,message:error instanceof Error?error.message:'Local site error'});}finally{aborters.delete(id);}})();});
  socket.on('preview:http:abort',(raw:unknown)=>{const id=(raw as {id?:string})?.id;if(id){aborters.get(id)?.();aborters.delete(id);}});
  const websockets=new Map<string,WebSocket>();
  socket.on('preview:ws:open',(raw:unknown,ack?:(reply:unknown)=>void)=>{const parsed=wsSchema.safeParse(raw),target=parsed.success?targets.get(parsed.data.subdomain):undefined;if(!parsed.success||!target||target.kind!=='port')return ack?.({ok:false});const {id,url,headers}=parsed.data;const client=new WebSocket(`ws://127.0.0.1:${target.port}${url}`,{headers:localHeaders(headers,target.port),handshakeTimeout:10000,maxPayload:2*1024*1024});websockets.set(id,client);let answered=false;client.once('open',()=>{answered=true;ack?.({ok:true});});client.on('message',(data,binary)=>socket.emit('preview:ws:frame',{id,data:Buffer.from(data as Buffer),binary}));client.on('close',()=>{websockets.delete(id);socket.emit('preview:ws:close',{id});});client.on('error',()=>{if(!answered){answered=true;ack?.({ok:false});}else client.close();});});
  socket.on('preview:ws:frame',(raw:unknown)=>{const parsed=z.object({id:z.string().uuid(),data:z.any(),binary:z.boolean()}).safeParse(raw);if(!parsed.success)return;const client=websockets.get(parsed.data.id);if(!client||client.readyState!==WebSocket.OPEN)return;const data=Buffer.isBuffer(parsed.data.data)?parsed.data.data:Buffer.from(parsed.data.data||[]);if(data.length<=2*1024*1024)client.send(data,{binary:parsed.data.binary});});
  socket.on('preview:ws:close',(raw:unknown)=>{const id=(raw as {id?:string})?.id;if(id)websockets.get(id)?.close();});
  socket.on('disconnect',()=>{for(const close of aborters.values())close();aborters.clear();for(const client of websockets.values())client.close();websockets.clear();});

  try{await unlink(controlFile);}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}
  const control=createServer(client=>{let buffer='';client.on('data',(chunk:Buffer)=>{buffer+=chunk.toString('utf8');if(buffer.length>8192){client.end(JSON.stringify({ok:false,error:'Слишком длинная команда'})+'\n');return;}if(!buffer.includes('\n'))return;const line=buffer.slice(0,buffer.indexOf('\n'));buffer='';void handleControl(client,line,socket);});});
  await new Promise<void>((resolve,reject)=>{control.once('error',reject);control.listen(controlFile,()=>resolve());});await chmod(controlFile,0o600);
}

async function handleControl(client:NetSocket,line:string,socket:Socket){const reply=(result:unknown)=>client.end(JSON.stringify(result)+'\n');try{const command=commandSchema.parse(JSON.parse(line));if(command.action==='list')return reply({ok:true,sites:[...targets.keys()]});if(!socket.connected)return reply({ok:false,error:'Runner не подключён к ai-router'});if(command.action==='stop'){const answer=await socket.timeout(10000).emitWithAck('preview:unregister',{subdomain:command.subdomain}) as {ok?:boolean};if(!answer.ok)return reply({ok:false,error:'Сайт не найден'});targets.delete(command.subdomain);await save();return reply({ok:true});}const target:Target=command.target.kind==='static'?{kind:'static',root:await checkedStaticRoot(command.target.root)}:command.target;const answer=await socket.timeout(10000).emitWithAck('preview:register',{subdomain:command.subdomain,renew:true}) as {ok?:boolean;url?:string;visible?:boolean;expiresAt?:string;error?:string};if(!answer.ok)return reply({ok:false,error:answer.error||'Не удалось опубликовать'});targets.set(command.subdomain,target);await save();reply({ok:true,url:answer.url,visible:answer.visible,expiresAt:answer.expiresAt});}catch(error){reply({ok:false,error:error instanceof Error?error.message:'Ошибка публикации'});}}
